### ISSUE TITLE
HdrHistogram_c : different target name 

### ISSUE THREAD

**Issue by julio77it** [raitechnology/natsrv#1]
Hi, while compiling I've got this error : 

make[1]: Leaving directory '/home/CKUguagiu/github/natsrv/sassrv'
make: *** No rule to make target 'sassrv/HdrHistogram_c/LINUX4.18.0_x86_64/lib64/libhdrhist.a', needed by 'everything'.  Stop.

These are the steps : 

$ git clone https://github.com/raitechnology/natsrv
$ cd natsrv
$ git submodule update --init --recursive
$ make

I've manually compiled the dependency, moved and renamed for let the compile works.

Thanks

**Comment by injinj** [comment]
Thanks, looks like a missing dependency.

I can get it to compile by

$ git clone https://github.com/raitechnology/natsrv
$ cd natsrv
$ git submodule update --init --recursive
$ cd sassrv/HdrHistogram_c
$ make
$ cd ../..
$ make

**Comment by injinj** [comment]
Fixed the dependency, should work now
